# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
vgsList = [
    ["v", false, ""],
    ["va", false, "Attack"],
        ["vat", false, "Tower"],
            ["vat1", true, "Attack Left Tower/Pheonix!"],
            ["vat2", true, "Attack middle Tower/Pheonix!"],
            ["vat3", true, "Attack right Tower/Pheonix!"],
        ["va1", true, "Attack Left lane!"],
        ["va2", true, "Attack middle lane!"],
        ["va3", true, "Attack right lane!"],
        ["vaa", true, "Attack!"],
        ["vaf", true, "Attack Fire Giant!"],
        ["vag", true, "Attack the Gold Fury!"],
        ["vam", true, "Attack the Titan!"],
        ["van", true, "Attack the Minions!"],
    ["vb", false, "Enemy"],
        ["vbj", false, "Jungle"],
            ["vbj1", true, "Enemies in the Left Jungle!"],
            ["vbj2", true, "Enemies in the right Jungle!"],
            ["vbjj", true, "Enemies in the Jungle!"],
        ["vb1", true, "Enemies in Left lane!"],
        ["vb2", true, "Enemies in middle lane!"],
        ["vb3", true, "Enemies in right lane!"],
        ["vba", true, "Enemy ultimate incomming!"],
        ["vbb", true, "Enemies have returned to base."],
        ["vbd", true, "Enemies ultimate down!"],
        ["vbe", true, "Enemies behind us!"],
        ["vbf", true, "Enemies at the Fire Giant!"],
        ["vbg", true, "Enemies at the Gold Fury!"],
        ["vbm", true, "Enemies at the Titan!"],
        ["vbs", true, "Enemy spotted!"],
    ["vc", false, "Careful"],
        ["vc1", true, "Be carful left lane!"],
        ["vc2", true, "Be carful middle lane!"],
        ["vc3", true, "Be carful right lane!"],
        ["vcb", true, "Return to base!"],
        ["vcc", true, "Be careful!"],
        ["vcj", true, "Be careful in the jungle!"],
    ["vd", false, "Defend"],
        ["vd1", true, "Defend left lane!"],
        ["vd2", true, "Defend middle lane!"],
        ["vd3", true, "Defend right lane!"],
        ["vdf", true, "Defend the Fire Giant!"],
        ["vdg", true, "Defend the Gold Fury!"],
        ["vdm", true, "Defend the Titan!"],
    ["ve", false, "Emote"],
        ["vea", true, "Awsome!"],
        ["veg", true, "I'm the Greatest!"],
        ["vej", true, "'Joke'"],
        ["vel", true, "Laugh"],
        ["ver", true, "You Rock!"],
        ["vet", true, "Taunt"],
        ["vew", true, "Woohoo!"],
    ["vf", false, "MIA"],
        ["vf1", true, "Enemy missing left!"],
        ["vf2", true, "Enemy missing middle!"],
        ["vf3", true, "Enemy missing right!"],
        ["vff", true, "Enemy missing!"],
    ["vg", false, "Gank"],
        ["vg1", true, "Gank left lane!"],
        ["vg2", true, "Gank middle lane!"],
        ["vg3", true, "Gank right lane!"],
        ["vgg", true, "Gank!"],
    ["vh", false, "Help"],
        ["vh1", true, "Help left lane!"],
        ["vh2", true, "Help middle lane!"],
        ["vh3", true, "Help right lane!"],
        ["vhh", true, "Help!"],
        ["vhs", true, "Need Healing!"],
    ["vi", false, "Incoming"],
        ["vi1", true, "Enemies incoming left!"],
        ["vi2", true, "Enemies incoming middle!"],
        ["vi3", true, "Enemies incoming right!"],
        ["vii", true, "Enemies incoming!"],
    ["vq", false, "Ward"],
        ["vq1", true, "Ward left!"],
        ["vq2", true, "Ward middle!"],
        ["vq3", true, "Ward right!"],
        ["vqf", true, "Ward Fire Giant!"],
        ["vqg", true, "Ward Gold Fury!"],
        ["vqn", true, "Need Wards!"],
        ["vqq", true, "Ward Here!"],
    ["vr", false, "Retreat"],
        ["vr1", true, "Retreat left lane!"],
        ["vr2", true, "Retreat middle lane!"],
        ["vr3", true, "Retreat right lane!"],
        ["vrj", true, "Retreat from the Jungle!"],
        ["vrr", true, "Retreat!"],
        ["vrs", true, "Save yourself!"],
    ["vs", false, "Self"],
        ["vsa", false, "Attack"],
            ["vsa1", true, "I'll attack left lane!"],
            ["vsa2", true, "I'll attack middle lane!"],
            ["vsa3", true, "I'll attack right lane!"],
            ["vsaa", true, "I'll attack!"],
            ["vsaf", true, "I'll attack Fire Giant!"],
            ["vsag", true, "I'll attack the Gold Fury!"],
            ["vsam", true, "I'll attack the Titan!"],
        ["vsb", false, "Buff"],
            ["vsbb", true, "I'm going for jungle buff!"],
            ["vsbn", true, "I need jungle buff."],
            ["vsbt", true, "Take this jungle buff."],
        ["vsd", false, "Defend"],
            ["vsd1", true, "I'll defend left lane!"],
            ["vsd2", true, "I'll defend middle lane!"],
            ["vsd3", true, "I'll defend right lane!"],
            ["vsdd", true, "I'll defend!"],
            ["vsdf", true, "I'll defend Fire Giant!"],
            ["vsdg", true, "I'll defend the Gold Fury!"],
            ["vsdm", true, "I'll defend the Titan!"],
        ["vsw", false, "Ward"],
            ["vsw1", true, "I will ward left!"],
            ["vsw2", true, "I will ward middle!"],
            ["vsw3", true, "I will ward right!"],
            ["vswq", true, "I will ward!"],
        ["vsg", false, "Gank"],
            ["vsg1", true, "I'll gank left lane!"],
            ["vsg2", true, "I'll gank middle lane!"],
            ["vsg3", true, "I'll gank right lane!"],
            ["vsgg", true, "I'll gank!"],
        ["vst", false, "Returned"],
            ["vst1", true, "I'm returning left lane!"],
            ["vst2", true, "I'm returning middle lane!"],
            ["vst3", true, "I'm returning right lane!"],
            ["vstb", true, "I'm returning to base!"],
            ["vstt", true, "I have returned!"],
        ["vso", true, "I'm on it!"],
        ["vsr", true, "Falling back!"],
        ["vss", true, "I'm building Stacks!"],
    ["vt", false, "Returned"],
        ["vt1", true, "Enemies have returned left!"],
        ["vt2", true, "Enemies have returned middle!"],
        ["vt3", true, "Enemies have returned right!"],
        ["vtt", true, "Enemies have returned!"],
    ["vv", false, "Other"],
        ["vvg", false, "General"],
            ["vvgb", true, "Bye!"],
            ["vvgf", true, "Have fun!"],
            ["vvgg", true, "Good game!"],
            ["vvgh", true, "Hi!"],
            ["vvgl", true, "Good luck!"],
            ["vvgn", true, "Nice job!"],
            ["vvgo", true, "Oops!"],
            ["vvgq", true, "Quiet!"],
            ["vvgr", true, "No problem!"],
            ["vvgs", true, "Curses!"],
            ["vvgt", true, "That's too bad!"],
            ["vvgw", true, "Your're welcome"],
        ["vvv", false, "Position"],
            ["vvva", true, "Set up an ambush here!"],
            ["vvvb", true, "Behind us!"],
            ["vvvc", true, "Chase the enemy!"],
            ["vvvd", true, "Ultimate is down!"],
            ["vvve", true, "On my way!"],
            ["vvvf", true, "Follow me!"],
            ["vvvg", true, "Group up!"],
            ["vvvj", true, "Going into the jungle!"],
            ["vvvp", true, "Split push!"],
            ["vvvr", true, "Ultimate is ready!"],
            ["vvvs", true, "Stay here!"],
            ["vvvt", true, "It's a trap!"],
            ["vvvw", true, "Place a Ward for teleport!"],
            ["vvvx", true, "Spread Out!"],
        ["vva", true, "Ok!"],
        ["vvb", true, "Be right back!"],
        ["vvc", true, "Completed!"],
        ["vvk", true, "Stepping away for a moment."],
        ["vvm", true, "Out of mana!"],
        ["vvn", true, "No!"],
        ["vvp", true, "Please?"],
        ["vvs", true, "Sorry!"],
        ["vvt", true, "Thanks!"],
        ["vvw", true, "Wait!"],
        ["vvx", true, "Cancel that!"],
        ["vvy", true, "Yes!"]
]

Element.destroy_all

vgsList.each do |line|
    Element.create({combo: line[0], final: line[1], value: line[2]})
end